jenkins:
  image: test:1 
  environment:
    ADOP_LDAP_ENABLED: "true"
    ADOP_GITLAB_ENABLED: "true"
    GITLAB_HOST_NAME: "gitlab"
    GITLAB_HTTP_URL: "http://gitlab/gitlab"
    GITLAB_ADMIN_USER: "root"
    GITLAB_ADMIN_PASSWORD: "${PASSWORD_GITLAB}"
    ADOP_GERRIT_ENABLED: "false"
    NEXUS_HTTP_URL: "http://nexus:8081/nexus"
    ADOP_SONAR_ENABLED: "false"
    SONAR_SERVER_URL: "http://sonar:9000/sonar"
    JENKINS_OPTS: "--prefix=/jenkins -Djenkins.install.runSetupWizard=false "
    JAVA_OPTS: "-Dpermissive-script-security.enabled=no_security"
    LDAP_ROOTDN: "$LDAP_FULL_DOMAIN"
    ADOP_SMTP_ENABLED: "false"
    LDAP_MANAGER_DN: "cn=admin,$LDAP_FULL_DOMAIN"
    LDAP_MANAGER_PASSWORD: "${LDAP_PWD}"
    LDAP_USER_SEARCH_BASE: "ou=people"
    LDAP_GROUP_SEARCH_BASE: "ou=groups"
    SUB_DOMAIN: "${SUB_DOMAIN}"
    INITIAL_ADMIN_USER: "${INITIAL_ADMIN_USER}"
    INITIAL_ADMIN_PASSWORD: "${INITIAL_ADMIN_PASSWORD_PLAIN}"
    GIT_SERVER_HOST_NAME: "gitlab"
    GIT_SERVER_PORT: "22"
    GIT_USERNAME: "jenkins"
    GIT_PASSWORD: "${PASSWORD_JENKINS}"
    USE_SCRIPT_SECURITY: "false"
    
proxy:
  image: migueltanada/adop-nginx:0.1
  environment:
    GIT_REPO: "gitlab"

jenkins-slave:
  environment:
    PASSWORD_GITLAB: "${PASSWORD_GITLAB}"
    PUBLIC_IP: "${PUBLIC_IP}"

gitlab:
  container_name: gitlab
  restart: always
  image: gitlab/gitlab-ce:10.1.1-ce.0
  net: ${CUSTOM_NETWORK_NAME}
  expose:
    - "80"
    - "443"
    - "22"
  volumes:
    - gitlab_etc:/etc/gitlab
    - gitlab_opt:/var/opt/gitlab
    - gitlab_log:/var/log/gitlab
  environment:
    GITLAB_ROOT_PASSWORD: ${PASSWORD_GITLAB}
    GITLAB_OMNIBUS_CONFIG: |
      external_url 'http://${PUBLIC_IP}/gitlab'
      gitlab_rails['smtp_enable'] = '${ADOP_SMTP_ENABLED}'
      gitlab_rails['smtp_address'] = 'mail-server'
      gitlab_rails['smtp_port'] = 25
      gitlab_rails['smtp_user_name'] = '${INITIAL_ADMIN_USER}@${LDAP_DOMAIN}'
      gitlab_rails['smtp_password'] = '${INITIAL_ADMIN_PASSWORD_PLAIN}'
      gitlab_rails['smtp_domain'] = '${SMTP_DOMAIN}'
      gitlab_rails['smtp_authentication'] = 'login'
      gitlab_rails['smtp_enable_starttls_auto'] = true
      gitlab_rails['smtp_openssl_verify_mode'] = 'peer'
      gitlab_rails['ldap_enabled'] = true
      gitlab_rails['ldap_servers'] = YAML.load <<-'EOS'
        main:
          label: 'LDAP'
          host: ldap
          port: 389
          uid: 'uid'
          method: 'plain'
          bind_dn: 'cn=admin,${LDAP_FULL_DOMAIN}'
          password: '${LDAP_PWD}'
          active_directory: false
          allow_username_or_email_login: false
          block_auto_created_users: false
          base: '${LDAP_FULL_DOMAIN}'
      EOS
